class UserDoesNotExist(Exception):...
class CategoryDoesNotExist(Exception):...
class EquipmentDoesNotExist(Exception):...
class HistoryDoesNotExist(Exception):...
class TransferDoesNotExist(Exception):...
class ActionDoesNotExist(Exception):...
