class UserDoesNotExists(Exception):...
class CategoryDoesNotExists(Exception):...
class EquipmentDoesNotExists(Exception):...
class HistoryDoesNotExists(Exception):...
class TransferDoesNotExists(Exception):...
class ActionDoesNotExists(Exception):...
